//HintName: BasicBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class BasicBuilder
{
	private bool _IsRequired_isSet;
	private string _IsRequired = default;
	public BasicBuilder WithIsRequired(string value)
	{
		_IsRequired = value;
		_IsRequired_isSet = true;
		return this;
	}
	private bool _StringInit_isSet;
	private string _StringInit = default;
	public BasicBuilder WithStringInit(string value)
	{
		_StringInit = value;
		_StringInit_isSet = true;
		return this;
	}
	private bool _NumberInit_isSet;
	private int _NumberInit = default;
	public BasicBuilder WithNumberInit(int value)
	{
		_NumberInit = value;
		_NumberInit_isSet = true;
		return this;
	}
	private bool _Standard_isSet;
	private string _Standard = default;
	public BasicBuilder WithStandard(string value)
	{
		_Standard = value;
		_Standard_isSet = true;
		return this;
	}
	public global::Basic Build()
	{
		var build = new global::Basic()
		{
			IsRequired = _IsRequired_isSet ? _IsRequired : throw new global::System.InvalidOperationException("Property \"IsRequired\" (string) must be set before build can be called."),
			StringInit = _StringInit_isSet ? _StringInit : default,
			NumberInit = _NumberInit_isSet ? _NumberInit : default
		};
		if (_Standard_isSet)
			build.Standard = _Standard;
		return build;
	}
	public static implicit operator global::Basic(BasicBuilder builder) => builder.Build();
}
