//HintName: PersonBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class PersonBuilder
{
	private bool _Name_isSet;
	private global::System.Lazy<string> _Name = new global::System.Lazy<string>(() => default);
	public PersonBuilder WithName(string value) => WithName(() => value);
	public PersonBuilder WithName(global::System.Func<string> func)
	{
		_Name = new global::System.Lazy<string>(func);
		_Name_isSet = true;
		return this;
	}
	private bool _Address_isSet;
	private global::System.Lazy<string> _Address = new global::System.Lazy<string>(() => default);
	public PersonBuilder WithAddress(string value) => WithAddress(() => value);
	public PersonBuilder WithAddress(global::System.Func<string> func)
	{
		_Address = new global::System.Lazy<string>(func);
		_Address_isSet = true;
		return this;
	}
	private bool _Age_isSet;
	private global::System.Lazy<int> _Age = new global::System.Lazy<int>(() => default);
	public PersonBuilder WithAge(int value) => WithAge(() => value);
	public PersonBuilder WithAge(global::System.Func<int> func)
	{
		_Age = new global::System.Lazy<int>(func);
		_Age_isSet = true;
		return this;
	}
	public global::Person Build()
	{
		return new global::Person()
		{
			Name = _Name_isSet ? _Name.Value : throw new global::System.InvalidOperationException("Property \"Name\" (string) must be set before build can be called."),
			Address = _Address_isSet ? _Address.Value : default,
			Age = _Age_isSet ? _Age.Value : default
		};
	}
}
