//HintName: ExternalPersonBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class ExternalPersonBuilder
{
	private bool _Name_isSet;
	private string _Name = default;
	public ExternalPersonBuilder WithName(string value)
	{
		_Name = value;
		_Name_isSet = true;
		return this;
	}
	private bool _Address_isSet;
	private string _Address = default;
	public ExternalPersonBuilder WithAddress(string value)
	{
		_Address = value;
		_Address_isSet = true;
		return this;
	}
	private bool _Age_isSet;
	private int _Age = default;
	public ExternalPersonBuilder WithAge(int value)
	{
		_Age = value;
		_Age_isSet = true;
		return this;
	}
	private bool _Nickname_isSet;
	private string _Nickname = default;
	public ExternalPersonBuilder WithNickname(string value)
	{
		_Nickname = value;
		_Nickname_isSet = true;
		return this;
	}
	public global::ExternalPerson Build()
	{
		var build = new global::ExternalPerson()
		{
			Name = _Name_isSet ? _Name : throw new global::System.InvalidOperationException("Property \"Name\" (string) must be set before build can be called."),
			Address = _Address_isSet ? _Address : default,
			Age = _Age_isSet ? _Age : default
		};
		if (_Nickname_isSet)
			build.Nickname = _Nickname;
		return build;
	}
}
