//HintName: NoGenerationBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class NoGenerationBuilder
{
	public global::NoGeneration Build()
	{
		var build = new global::NoGeneration()
		{
		};
		return build;
	}
}
