//HintName: CtorBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class CtorBuilder
{
	private global::System.Func<global::Ctor> _builder;
	public CtorBuilder(int number)
	{
		_builder = () => new(number)
		{
		};
	}
	public CtorBuilder(string name)
	{
		_builder = () => new(name)
		{
		};
	}
	public CtorBuilder(int number, string name)
	{
		_builder = () => new(number, name)
		{
		};
	}
	public CtorBuilder(int number, bool flag = true, string blank = null, string empty = "", string foo = "foo")
	{
		_builder = () => new(number, flag, blank, empty, foo)
		{
		};
	}
	public global::Ctor Build()
	{
		var build = _builder();
		return build;
	}
	public static implicit operator global::Ctor(CtorBuilder builder) => builder.Build();
}
