//HintName: ClassCBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ClassCBuilder
{
	private global::System.Func<global::ClassC> _builder;
	public ClassCBuilder()
	{
		_builder = () => new()
		{
		};
	}
	private bool _C_isSet;
	private string _C = default;
	public ClassCBuilder WithC(string value)
	{
		_C = value;
		_C_isSet = true;
		return this;
	}
	private bool _B_isSet;
	private string _B = default;
	public ClassCBuilder WithB(string value)
	{
		_B = value;
		_B_isSet = true;
		return this;
	}
	private bool _A_isSet;
	private string _A = default;
	public ClassCBuilder WithA(string value)
	{
		_A = value;
		_A_isSet = true;
		return this;
	}
	public global::ClassC Build()
	{
		var build = _builder();
		if (_C_isSet)
			build.C = _C;
		if (_B_isSet)
			build.B = _B;
		if (_A_isSet)
			build.A = _A;
		return build;
	}
	public static implicit operator global::ClassC(ClassCBuilder builder) => builder.Build();
}
