//HintName: ClassCBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ClassCBuilder
{
	private global::System.Func<global::ClassC> _builder;
	public ClassCBuilder()
	{
		_builder = () => new()
		{
		};
	}
	private bool _c_isSet;
	private string _c = default;
	public ClassCBuilder WithC(string value)
	{
		_c = value;
		_c_isSet = true;
		return this;
	}
	private bool _b_isSet;
	private string _b = default;
	public ClassCBuilder WithB(string value)
	{
		_b = value;
		_b_isSet = true;
		return this;
	}
	private bool _a_isSet;
	private string _a = default;
	public ClassCBuilder WithA(string value)
	{
		_a = value;
		_a_isSet = true;
		return this;
	}
	public global::ClassC Build()
	{
		var build = _builder();
		if (_c_isSet)
			build.C = _c;
		if (_b_isSet)
			build.B = _b;
		if (_a_isSet)
			build.A = _a;
		return build;
	}
	public static implicit operator global::ClassC(ClassCBuilder builder) => builder.Build();
}
