//HintName: PersonBuilder.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/pocoman
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class PersonBuilder
{
	private global::System.Func<global::Person> _builder;
	public PersonBuilder(string name)
	{
		_builder = () => new(name)
		{
			Honorific = _honorific_isSet ? _honorific : throw new global::System.InvalidOperationException("Property \"Honorific\" (string) must be set before build can be called."),
			Age = _age_isSet ? _age : default
		};
	}
	private bool _honorific_isSet;
	private string _honorific = default;
	public PersonBuilder WithHonorific(string value)
	{
		_honorific = value;
		_honorific_isSet = true;
		return this;
	}
	private bool _age_isSet;
	private int _age = default;
	public PersonBuilder WithAge(int value)
	{
		_age = value;
		_age_isSet = true;
		return this;
	}
	private bool _address_isSet;
	private string _address = default;
	public PersonBuilder WithAddress(string value)
	{
		_address = value;
		_address_isSet = true;
		return this;
	}
	public global::Person Build()
	{
		var build = _builder();
		if (_address_isSet)
			build.Address = _address;
		return build;
	}
	public static implicit operator global::Person(PersonBuilder builder) => builder.Build();
}
